#!/bin/sh

#
src=mol_conv
F77 = ifort 
#F77 = /usr/local/mpich/bin/mpif90
#F77 = /usr/local/mpich-intel81/bin/mpif90
#F77 = /usr/local/mpich-intel81/bin/mpif90
#F77 =  /usr/lang/mpi2/bin/mpifrt
# F77 = frt
RM=/bin/rm
CFLAGS =
#CFLAGS = -132 -w95 -w90 -d2 -C
#CFLAGS = -132 -w95 -w90 -static -O5 #-convert big_endian
#CFLAGS = -132 -w95 -w90 -W0 -O3 -tpp7
# CFLAGS =  -Of -Pdt -Em -Wv,-m3 -I./incl
#CFLAGS =  -Pdt -Dys -Em -Wv,-m3 -I./incl
#CFLAGS =  -Pdt -Ds -Em -Wv,-m3 -I./incl
#CFLAGS =  -Pdt -Ds -Em -Wv,-m3 -I./incl
#CFLAGS = -Pdt -Em -Wv,-m3 -I./incl
#CFLAGS = -Dasy -Pdt -Em -Wv,-m3 -I./incl
#CFLAGS = -Pdt -Em -Wv,-m3 -Wx -I./incl
#CFLAGS = -AT -Pdt -Em -Wv,-ad,-m3 -Wx,-Cd -I./incl
#LFLAGS = -Wx 
#LFLAGS = -static
LFLAGS =
VPP=1
MPI=1

OBJ = $(src).o
#SRCDIR = /home/masako/phys/NGC253/nonLTE_AGN_wada/src
#NRDIR = /home/masako/phys/NR
SRCDIR = .
NRDIR = .


all: ${src}

${src}.f: ${src}.F
#	/usr/bin/cpp -D VPP -D MPI ${src}.F > ${src}.f
	/usr/bin/cpp -C -D LINUX ${src}.F > ${src}.f
${src}.o: ${src}.f
	$(F77) $(CFLAGS)  -c -o $(src).o ${src}.f

#${src}: $(src).o
#	$(F77) $(LFLAGS) -o ${src} $(src).o
${src}: $(OBJ)
	$(F77) $(LFLAGS) -o ${src} $(OBJ)

clean: 
	$(RM) *.o
